import dictionary from 'an-array-of-english-words';

export const WORDS_6 = [
  "PLANET", "ROCKET", "STREAM", "FOREST", "ANIMAL", "GARDEN", 
  "SUMMER", "WINTER", "SPRING", "AUTUMN", "BRIDGE", "CASTLE", 
  "DRAGON", "KNIGHT", "SILVER", "GOLDEN", "ORANGE", "YELLOW", 
  "PURPLE", "SYSTEM", "NATURE", "PEOPLE", "FAMILY", "FRIEND", 
  "SCHOOL", "MARKET", "STREET", "TICKET", "WINDOW", "BOTTLE", 
  "BASKET", "BUTTON", "CAMERA", "COFFEE", "GUITAR", "ISLAND", 
  "JACKET", "JUNGLE", "LIZARD", "MONKEY", "PENCIL", "POCKET", 
  "RABBIT", "SAILOR", "TURTLE", "WALLET", "ZEBRAS", "ACTION", 
  "AGENCY", "ANSWER", "AROUND", "AUTHOR", "BEAUTY", "BEFORE", 
  "BOTTOM", "BRANCH", "BREATH", "BROKEN", "BUBBLE", "CAREER", 
  "CEMENT", "CHANCE", "CHANGE", "CHEESE", "CHURCH", "CIRCLE", 
  "CLEVER", "CLOSET", "COMMON", "CORNER", "COURSE", "COUSIN", 
  "CREDIT", "CUSTOM", "DAMAGE", "DANGER", "DEGREE", "DESIGN", 
  "DETAIL", "DEVICE", "DINNER", "DOCTOR", "DOLLAR", "DOUBLE", 
  "DRIVER", "EARTHY", "EFFECT", "EFFORT", "EIGHTH", "ENERGY", 
  "ENGINE", "ENOUGH", "ENTIRE", "ESTATE", "EXPERT", "FACTOR", 
  "FATHER", "FINGER", "FINISH", "FLIGHT", "FLOWER", "FORGET", 
  "FORMAL", "FORMER", "FUTURE", "GATHER", "GENDER", "GLOBAL", 
  "GROUND", "GROWTH", "HAPPEN", "HEALTH", "HEIGHT", "HIDDEN", 
  "HONEST", "HUNTER", "IGNORE", "IMPACT", "INCOME", "INJURY", 
  "INSIDE", "INVEST", "ITSELF", "KEEPER", "KISSES", "LABOUR", 
  "LADDER", "LATEST", "LAWYER", "LEADER", "LEAGUE", "LEAVES", 
  "LEGACY", "LENGTH", "LESSON", "LETTER", "LIQUID", "LISTEN", 
  "LITTLE", "LIVING", "LOVELY", "MAKING", "MANAGE", "MANNER", 
  "MASTER", "MATTER", "MEMORY", "MENTAL", "METHOD", "MIDDLE", 
  "MINUTE", "MIRROR", "MOBILE", "MODERN", "MOMENT", "MOTHER", 
  "MOTION", "MURDER", "MUSCLE", "MUSEUM", "MYSELF", "NATION", 
  "NOBODY", "NORMAL", "NOTICE", "NUMBER", "OBJECT", "OFFICE", 
  "ONLINE", "OPTION", "OTHERS", "OUTPUT", "PARENT", "PARISH", 
  "PASSIVE", "PASTEL", "PATENT", "PAYING", "PAYOUT", "PEANUT", 
  "PEPPER", "PERIOD", "PERSON", "PHRASE", "PICKLE", "PILLOW", 
  "PIRATE", "PLAYER", "PLEASE", "PLENTY", "POETRY", "POLICE", 
  "POLICY", "POSTER", "POTATO", "POWDER", "PREFER", "PRETTY", 
  "PRINCE", "PRISON", "PROFIT", "PROMPT", "PROPER", "PUBLIC", 
  "PUPPET", "PUZZLE", "QUOTES", "RADAR", "RANDOM", "REASON", 
  "RECORD", "REDUCE", "REFUSE", "REGION", "RELATE", "RELIEF", 
  "REMAIN", "REMOTE", "REMOVE", "REPAIR", "REPEAT", "REPLAY", 
  "REPORT", "RESCUE", "RESORT", "RESULT", "RETURN", "REVEAL", 
  "REVIEW", "REWARD", "RHYTHM", "RIBBON", "RIDDLE", "RIDING", 
  "RITUAL", "ROBBER", "ROLLER", "ROMAN", "RUBBER", "RULING", 
  "RUMOUR", "RUNNER", "SAFARI", "SAFETY", "SALMON", "SAMPLE", 
  "SANDAL", "SAUCER", "SAVAGE", "SAVING", "SCARED", "SCENIC", 
  "SCHEME", "SCREAM", "SCREEN", "SCRIPT", "SEARCH", "SEASON", 
  "SECOND", "SECRET", "SECURE", "SELECT", "SENIOR", "SENSEI", 
  "SENSOR", "SERIES", "SERVER", "SETTLE", "SEVENT", "SEVERE", 
  "SHADOW", "SHAKEN", "SHAPED", "SHARED", "SHARK", "SHIELD", 
  "SHINED", "SHIRTS", "SHIVER", "SHOCKS", "SHOOTS", "SHORES", 
  "SHORTS", "SHOUTS", "SHRIMP", "SHRINK", "SHRUGS", "SIGHTS", 
  "SIGNAL", "SILENT", "SILVER", "SIMPLY", "SINGER", "SINGLE", 
  "SISTER", "SKETCH", "SKILLS", "SLICED", "SLIDER", "SLIGHT", 
  "SLOGAN", "SLOPE", "SMART", "SMILED", "SMOOTH", "SNAKES", 
  "SNEAKY", "SNIPER", "SNOWED", "SOCCER", "SOCIAL", "SOCKET", 
  "SODIUM", "SOFTLY", "SOLVED", "SORROW", "SORTED", "SOURCE", 
  "SPACED", "SPARKS", "SPEAKS", "SPEECH", "SPEEDY", "SPELLS", 
  "SPIDER", "SPIRIT", "SPOILS", "SPOKEN", "SPONGE", "SPOONS", 
  "SPORTS", "SPREAD", "SPRING", "SQUARE", "SQUASH", "STABLE", 
  "STRIKE", "STRING", "STROKE", "STRONG", "STRUCK", "STUDIO", 
  "SUBMIT", "SUDDEN", "SUFFER", "SUMMER", "SUMMIT", "SUNSET", 
  "SUPPLY", "SURELY", "SURVEY", "SWITCH", "SYMBOL", "SYSTEM", 
  "TABLET", "TACKLE", "TAILOR", "TALENT", "TARGET", "TASTED", 
  "TATTOO", "TAVERN", "TEMPLE", "TENNIS", "TENSION", "TERROR", 
  "THEORY", "THINGS", "THIRTY", "THREAT", "THRILL", "THROAT", 
  "TICKET", "TIMBER", "TIMING", "TISSUE", "TOILET", "TOMATO", 
  "TONGUE", "TOOTH", "TOPICS", "TOPPED", "TOSSED", "TOTALS", 
  "TOWARD", "TOWELS", "TOWERS", "TRACED", "TRACKS", "TRADED", 
  "TRAGIC", "TRAILS", "TRAINS", "TRAITS", "TRANCE", "TRAVEL", 
  "TREATS", "TREATY", "TRENDS", "TRIALS", "TRIBAL", "TRICKS", 
  "TRIPLE", "TROOPS", "TROPHY", "TRUCKS", "TRUSTS", "TRUTHS", 
  "TRYING", "TUNNEL", "TURKEY", "TURNED", "TWELVE", "TWENTY", 
  "TYPING", "UNABLE", "UNCLES", "UNIQUE", "UNLESS", "UNLIKE", 
  "UNSEEN", "UNTIED", "UPDATE", "UPHOLD", "UPWARD", "URGENT", 
  "USEFUL", "VACANT", "VALLEY", "VALUES", "VANISH", "VECTOR", 
  "VELVET", "VENDOR", "VERBAL", "VERIFY", "VERSUS", "VESSEL", 
  "VICTIM", "VICTOR", "VIDEOS", "VIEWER", "VIKING", "VILLAGE", 
  "VINYL", "VIRTUE", "VISION", "VISITS", "VISUAL", "VOICES", 
  "VOLUME", "VOTING", "VOYAGE", "WAFERS", "WAGONS", "WAITED", 
  "WAIVER", "WAKING", "WALKED", "WALLET", "WALNUT", "WANDER", 
  "WANTED", "WARMED", "WARNED", "WARREN", "WASHED", "WASTED", 
  "WATCH", "WATER", "WEALTH", "WEAPON", "WEAVER", "WEBCAM", 
  "WEEKLY", "WEIGHT", "WEIRD", "WHALES", "WHEELS", "WHILST", 
  "WHOLE", "WICKED", "WIDELY", "WIDOWS", "WILDLY", "WILLOW", 
  "WINDOW", "WINNER", "WINTER", "WIPING", "WIRED", "WISDOM", 
  "WISHED", "WISHES", "WITHIN", "WIZARD", "WOLVES", "WOMEN", 
  "WONDER", "WOODEN", "WORKED", "WORKER", "WORLDS", "WORTHY", 
  "WOUNDS", "WRITER", "WRITES", "YEARLY", "YELLOW", "YIELDS", 
  "YOUTH", "ZEBRAS", "ZIGZAG", "ZIPPED", "ZOMBIE", "ZONING"
];

const VALID_WORDS_SET = new Set<string>();

// Add our explicit 6-letter words to the valid set
WORDS_6.forEach(word => VALID_WORDS_SET.add(word));

// Add all 6-letter words from the dictionary
if (Array.isArray(dictionary)) {
  dictionary.forEach(word => {
    if (typeof word === 'string' && word.length === 6) {
      VALID_WORDS_SET.add(word.toUpperCase());
    }
  });
}

export function getRandomWord(): string {
  return WORDS_6[Math.floor(Math.random() * WORDS_6.length)].toUpperCase();
}

export function isValidWord(word: string): boolean {
  return VALID_WORDS_SET.has(word.toUpperCase());
}
